#!/bin/bash

set -e -u

iso639=sme
bcp47=se
package=giella-"${iso639}"
pipename="${iso639}"spell
modename="${iso639}"-"${iso639}"_spell

export PREFIX="$HOME/divvun/PREFIX/"
export PATH="$PREFIX/bin:$PATH"

echo "$(date -R)	$0: starting"

# Run everything from a tempdir which we remove on exit:
tmpdir=$(mktemp -d -t divvun-updater.XXXXXXXXXX)
trap 'rm -rf "${tmpdir}"' EXIT
cd "${tmpdir}"

# Ensure we have a UTF-8 locale (at least some hfst tools need this)
LC_ALL=$(locale -a|grep UTF-8|head -1)
export LC_ALL

# Pick the "latest" distro:
dists=$(curl -Ss 'https://apertium.projectjj.com/apt/nightly/dists/?C=M;O=A')
dist=$(awk -F'href="|"' '/<tr><td><a href/&&$2{u=$2}END{print u}' <<<"${dists}")

# Find our package in that distro:
packages=$(curl -Ss https://apertium.projectjj.com/apt/nightly/dists/"${dist}"/main/binary-amd64/Packages)
pool=$(awk -v package="${package}" '/^Package:/{p=($2 == package)} p && /^Filename:/{print $2;exit}' <<< "${packages}")
url=https://apertium.projectjj.com/apt/nightly/"${pool}"

curl "${url}" >"${package}.deb"

ar x "${package}.deb"

zcheck=./usr/share/voikko/4/"${bcp47}".zcheck
for f in data.tar.*; do
    tar xf "$f" "${zcheck}"
done

sanity_grep () {
    if ! grep -q "$2" <<<"$3"; then
        echo "$(date -R)	$0: ERROR: Couldn't find $2 in $3 when running test '$1', updating failed" >&2
        exit 65
    fi
}

# Fail if we don't give any error message for space-before-punct-mark:
# (assuming all languages mark this as an error for their default pipeline …)
res=$(echo ' .' | divvun-checker --archive "${zcheck}")
sanity_grep "zcheck" '".",1,2' "${res}"

# Fail if pipename in pipespec doesn't give any JSON (though we can't
# expect an error for ' .' here):
mkdir -p data
unzip -d data "${zcheck}"
if [[ ! -f data/spellchecker.bin ]]; then
    # TODO: currently missing from zcheck:
    cg-comp "${HOME}"/divvun/PREFIX/share/giella/"${iso639}"/spellchecker.cg3 data/spellchecker.bin
fi
# apertium-apy expects no shebangs nor newlines, should be fixed
# upstream but workaround for now:
divvun-gen-sh -j data/pipespec.xml "${pipename}" \
    | grep -v '^#'                               \
    | tr '\n' ' '                                \
    | sed 's/\\ //g'                             \
    > "${modename}".mode
res2=$(echo '.' | sh "${modename}".mode)
sanity_grep "simple" '"text":".\\n"' "${res2}"

# mode-specific tests:
case $pipename in
    smespell)
        res_s=$(echo 'sátnejodiheaddji' | sh "${modename}".mode)
        sanity_grep "Err/Orth" 'sátnejođiheaddji' "${res_s}"
        res_s2=$(echo 'stnejodiheaddji' | sh "${modename}".mode)
        sanity_grep "speller" 'sátnejođiheaddji' "${res_s2}"
        res_s3=$(echo 'Finnmarku' | sh "${modename}".mode)
        sanity_grep "Err/orth-a-á" 'Finnmárku' "${res_s3}"
    ;;
esac


# If we got this far, extract into the right place:
export DATADIR="${PREFIX}/share/giella/${iso639}"
export MODESDIR="${PREFIX}/share/apertium/modes"
mkdir -p "${DATADIR}"
rsync -avh --update data/ "${DATADIR}"/
mkdir -p "${MODESDIR}"
divvun-gen-sh -j "${DATADIR}"/pipespec.xml "${pipename}" \
    | grep -v '^#'                                       \
    | tr '\n' ' '                                        \
    | sed 's/\\ //g'                                     \
    > "${MODESDIR}"/"${modename}".mode
echo "$(date -R)	$0: Installed new language data"
res3=$(echo '.' | sh "${MODESDIR}"/"${modename}".mode)
sanity_grep "installed mode" '"text":".\\n"' "${res3}"

echo "$(date -R)	$0: Successfully updated divvun giella-${iso639} language data -- apy will use it next time it restarts the pipe"
